- args:
    sql: COMMENT ON COLUMN "public"."audit"."configSettings" IS ''
  type: run_sql
- args:
    sql: alter table "public"."audit" rename column "configSettings" to "config_settings";
  type: run_sql
